### ISSUE TITLE
Tasks always queued

### ISSUE THREAD

**Issue by jorrete** [uptick/django-cq#11]
Hello,
I am asking for some help with the conf. I've configured my settings according with the docs and run cq_worker along runserver.  The task appear in admin but always queued, it seems that the worker it is not consuming the tasks. Am i missing something?
Thanks.

**Comment by furious-luke** [comment]
Hi there,

It's pretty tough to debug without actually seeing the system, as there are a number of places where things can go wrong. However there are some basic things to check:

 * Is your Redis server running and connected via the Django settings?

 * Is your CQ channel layer configured to the correct Redis URL?

 * Have you set `CQ_CHANNEL_LAYER` to the correct value?

 * Is Django Channels setup and running as expected?

If you're still having troubles, perhaps you could send me your settings file to take a look at (not forgetting to redact any secret info)?

Cheers,
Luke

**Comment by jorrete** [comment]
I managed to get working. If a set CQ_CHANNEL_LAYER = 'default' instead of 'long' it works.
I'm testing with django runserver and a worker in my local machine.

**Comment by furious-luke** [comment]
Ah, sounds like you may not have created a long Channel layer. If you want to use a layer with a longer timeout for your background tasks you can use something like this:

```
CHANNEL_LAYERS = {
    'default': { ... },
    'long': {
        'BACKEND': 'redis_channel_layer.DjangoRedisChannelLayer',  # use cache connection
        'CONFIG': {
            'hosts': [REDIS_URL],
            'expiry': 1800,  # 30 minutes before removal
            'channel_capacity': {
                'cq-tasks': 1000
            }
        },
        'ROUTING': '...'
    },
}
```

I've used an ellipses to indicate things I've left out.

**Comment by jorrete** [comment]
I have created it. I copied the example, and I checked with DTD and it seems ok. If swap the names between 'default' and 'long' it workrs (with CQ_CHANNEL_LAYER = 'default'). But as soon I keep the two layers default and long and set CQ_CHANNEL_LAYER = 'long' it stop to consume tasks.

[settings.txt](https://github.com/furious-luke/django-cq/files/1400176/settings.txt)

**Comment by furious-luke** [comment]
Sorry I deleted your comment there, but the settings file you sent included passwords, probably best to remove any references to passwords/usernames when sending example files.

Also, sorry to be a pain, but can you send me an example settings file that includes the exact setup that's failing? The one you sent was configured to use the `default` channel. I'd like to see specifically what you're using when it fails.

Thanks!

**Comment by jorrete** [comment]
Thanks I am the worst.
[settings_cq.txt](https://github.com/furious-luke/django-cq/files/1400216/settings_cq.txt)

**Comment by furious-luke** [comment]
So it looks like `CQ_CHANNEL_LAYER` is still set to `default` in that file, I'm assuming that is supposed to be set to `long`.

So, one other thing to check, when you launch your background worker what command are you using?

**Comment by jorrete** [comment]
Yes, that is correct, it  is set to 'long'.
```
 ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
October 19, 2017 - 22:57:20
Django version 1.11.6, using settings 'config.settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
2017-10-19 22:57:20,391 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-10-19 22:57:20,392 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-10-19 22:57:20,393 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-10-19 22:57:20,393 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-10-19 22:57:20,394 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2017-10-19 22:57:20,394 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-10-19 22:57:20,395 - INFO - server - Listening on endpoint tcp:port=8000:interface=127.0.0.1


./manage.py cq_runworker

2017-10-19 22:58:11,415 - INFO - runworker - Using single-threaded worker.
2017-10-19 22:58:11,415 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-10-19 22:58:11,421 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive


```

**Comment by furious-luke** [comment]
Ah, looks like your worker is running on the `default` channel, not `long`:

` Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)`

Interesting.... was that output above generated with a setting of `CQ_CHANNEL_LAYER="long"`?

**Comment by jorrete** [comment]
The same.
```
./manage.py cq_runworker

2017-10-19 23:06:28,946 - INFO - runworker - Using single-threaded worker.
2017-10-19 23:06:28,946 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-10-19 23:06:28,952 - INFO - worker - Listening on channels cq-tasks, http.request, websocket.connect, websocket.disconnect, websocket.receive


Django |   | 1.11.6
-- | -- | --
Python |   | 3.5.4
channels | Channels | 1.1.8
corsheaders | Corsheaders | 2.1.0
dbbackup | Backup and restore | 3.2.0
debug_toolbar | Debug Toolbar | 1.8
django_extensions | Django_Extensions | 1.9.6
easy_thumbnails | Easy_Thumbnails | <module 'easy_thumbnails.get_version' from  '/home/jorro/Development/projects/hikeorama/root/lib64/python3.5/site-packages/easy_thumbnails/get_version.py'>
flat_responsive | Flat_Responsive | 2.0
registration | Registration | 1.8
rest_framework | Django REST framework | 3.7.1
rest_framework_gis | Rest_Framework_Gis | 0.11.2
rest_framework_jwt | Rest_Framework_Jwt | 1.11.0
rosetta | Rosetta | 0.7.13


```

**Comment by furious-luke** [comment]
Okay, so it looks like `cq_worker` isn't registering it should be listening on the `long` channel. Can you try running the worker like this:

`./manage.py cq_runworker --layer=long`

**Comment by jorrete** [comment]
It works. Does it means that cq_worker only will listen to 'long' layer?

**Comment by furious-luke** [comment]
Yep, correct. When you specify `CQ_CHANNEL_LAYER=long` it indicates CQ messages will only be sent out over the "long" layer. `--layouer=long` needs to be given to the worker to tell it to listen on that layer. I'll update the README to reflect this. Thanks for the bug report!

**Comment by jorrete** [comment]
Thanks to you for your work and patience.

**Comment by furious-luke** [comment]
Actually, I've changed my mind, what I'll do is alter the `cq_runworker` command to automatically select the layer based on `CQ_CHANNEL_LAYER`. I'll let you know via this issue once it's done.

**Comment by furious-luke** [comment]
Okay, I've pushed a change to the repo, you shouldn't have to supply `--layer=long` anymore. If you specify `CQ_CHANNEL_LAYER="long"` in your settings you can just use:

```
./manage.py cq_runworker
```

And it should automatically use the "long" layer.

**Comment by furious-luke** [comment]
I'm going to close this issue, if you find my changes aren't working please reopen.
