### ISSUE TITLE
Unable to migrate after configuring cq

### ISSUE THREAD

**Issue by ahmadore** [uptick/django-cq#13]
Trying to run .**/migrate** with python3 after configuring cq, but it keeps breaking, an issue with the database backend. It fails with this error at the end...
_sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type_
Any ideas please??

**Comment by furious-luke** [comment]
Hi there, that error is most likely a result of CQ using JSON field types in its models. Take a look at this sqlite extension:

https://www.sqlite.org/json1.html

You may need to try installing that, or perhaps swapping to a more fully featured database backend.

**Comment by ahmadore** [comment]
Thank you very much. Will check it ASAP and get back to you on how it goes.

**Comment by ahmadore** [comment]
It worked, i changed the database backend to postgres. Thank you
