### ISSUE TITLE
ImportError: cannot import name 'worker_process_ready'

### ISSUE THREAD

**Issue by papasax** [uptick/django-cq#18]
Hi,

I try to use django-cq with Channels 2.x series.
When i launch ./manage.py i get this error:
File "/Users/papasax/.pyenv/versions/powerplantes-env-3.6.4/lib/python3.6/site-packages/cq/apps.py", line 7, in <module>
    from channels.signals import worker_process_ready
ImportError: cannot import name 'worker_process_ready'

is django-cq ready for Channels 2.x series?

**Comment by jarekwg** [comment]
There was a channels2 branch floating around. It's now merged into master and out in version django-cq v0.2.0
