### ISSUE TITLE
"channels" not in install_requires of setup.py?

### ISSUE THREAD

**Issue by guettli** [uptick/django-cq#19]
I wanted to know which version of channels library you use (1.x or 2.x).

I looked into the setup.py but could not find it in install_requires.

Is this intended?

**Comment by jarekwg** [comment]
Use 2.x. Can't answer why it's not in the install_requires, but you can add it as a direct dependency in your own project.

**Comment by jarekwg** [comment]
Added requirement to setup.py in 2e9433df9f8794179f072e77fc13e352408e2325
