### ISSUE TITLE
_receive_many_list_names is... not a thing.

### ISSUE THREAD

**Issue by ryanmcgrath** [uptick/django-cq#2]
Hey,

Love the idea/project. Noticed two things running it:

- Your imports in `consumers.py` cause some issues with newer Django/Channels. Changing them ala https://github.com/ryanmcgrath/django-cq/commit/99215f8ab975075e01966c7e444978f5c3e1023a handled it fine for me.
- In your backend object, in `get_queued_tasks`, you're calling `cl._receive_many_list_names` (`cl` being a ChannelLayer). This method doesn't seem to exist in Channels insofar as I can see, and it's broken as a result.

**Comment by furious-luke** [comment]
Hi there,
Thanks for the issue report! My guess is channels has undergone a few changes. I'm using CQ on  various servers at the moment, but have it frozen at a particular commit. I'll unfreeze it to use the latest and see how I go.
Cheers,
Luke

**Comment by furious-luke** [comment]
Hi again,
I've modified the master branch to work with the latest version of asgi_redis (that's where the issue was originating). Let me know if it works for you.
Cheers,
Luke

**Comment by ryanmcgrath** [comment]
Hey,

Yeah, I actually did the same in my fork earlier. Nice!

- Ryan

--
Ryan McGrath
ryan@rymc.io | https://rymc.io/
[image: Twitter] <https://twitter.com/ryanmcgrath/> [image: LinkedIn]
<https://linkedin.com/in/ryanmcgrathr> [image: Dribble]
<https://dribbble.com/ryanmcgrath/> [image: Skype]
<https://rymc.io/skype/> [image:
Github] <https://github.com/ryanmcgrath/>

**Comment by furious-luke** [comment]
Sweet.

P.S. Please feel free to submit any PRs for cool stuff you do with your branch. :smile:
