### ISSUE TITLE
Depency django-redis missing

### ISSUE THREAD

**Issue by jgadelange** [uptick/django-cq#5]
This package is dependent on `django-redis`, but currently it is not installed automatically or mentioned in the README.md. 

I believe this should be added either in:
 * `setup.py` as a dependency of the package (I think this is the best method), or
 * `README.md` under the installation header

Could you give the preferred method so I can create a PR?

**Comment by furious-luke** [comment]
Ah, sorry, totally missed this issue in my feed.

Preferably should go in `setup.py` so it's installed automatically. At the moment it's required as Redis is the only supported backend. Thanks!

**Comment by jarekwg** [comment]
Added in Added requirement to setup.py in 2e9433df9f8794179f072e77fc13e352408e2325
