### ISSUE TITLE
Brainstorming: Replacement for Nagio-like application?

### ISSUE THREAD

**Issue by guettli** [uptick/django-cq#8]
... This is just brainstorming.

We run a custom application for server monitoring. 

It supports the very simple nagios plugin API. A script uses exit status code 0=OK, 1=Warn, 2=ERR, 3=CRITICAL and some stdout.

I am unhappy with it since several years, but found not better solution.

I think django-cq could be used for this kind of application.

Don't get me wrong. I don't want server monitoring inside django-cq, but it could be build by using it.

What do you think?

Do you have any experience with monitoring/nagios/checks?

**Comment by furious-luke** [comment]
Not so much I'm afraid, I'm not familiar with Nagios' plugin API.

I can't really comment on the applicability of CQ to such an application given my lack of experience with Nagios.

Django CQ is primarily useful as a background task queue, and also for distributed task scheduling. If you think those kinds of things might be useful in your application then it could be worth giving it a try.

Sorry I can't offer more advice.

**Comment by guettli** [comment]
Thank you. I think it should be possible to use django-cq for our nagios like application.

I checked the attributes of Task again. All needed attributes are there.

Thank you - I hope I am able to write a successful use case here in some months. Until then I close this issue. ok?
