### ISSUE TITLE
SKIP LOCKED for PostgreSQL

### ISSUE THREAD

**Issue by guettli** [uptick/django-cq#9]
For building work queues PostgreSQL offers SKIP LOCKED[1]

> The main utility of SKIP LOCKED is for building simple, reliable and efficient concurrent work queues.

Django supports this in [select_for_update()](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#django.db.models.query.QuerySet.select_for_update)

Do you use this feature? ... Since (according to Craig Ringer, author of the article [1]) "Most work queue implementations in SQL are wrong".

[1] SKIP LOCKED: 
https://blog.2ndquadrant.com/what-is-select-skip-locked-for-in-postgresql-9-5/

**Comment by furious-luke** [comment]
Nope, the work queue is implemented via Channels, so using a second work queue is probably a bit redundant.

**Comment by guettli** [comment]
Somewhere tasks need to get created and deleted in the database. At least I think so, because I see a model called "Task". I am looking at this part.

**Comment by furious-luke** [comment]
Yep, that's right, but the DB is not used as a work queue. The work queue is managed by the Channels transport, which in the case of CQ is Redis. The DB is used to record the state of an individual task, but is not used for the workers to determine what next to do.

**Comment by guettli** [comment]
I am new to Redis. Please forgive my naive question. 

Why is Redis needed? Why not just use the database?

I worked with transactions spanning multiple databases before. I would avoid it. I would use only one  system if possible.

**Comment by furious-luke** [comment]
Sorry for the delay in responding, totally missed this.

There are a couple of reasons to use Redis as a transport mechanism, but the one that's most relevant for CQ is that I wanted the system to be able to scale with the number of worker processes. If there were hundreds of worker processes all connected to the database, each of them polling the database for new tasks every few seconds, I suspect the DB performance may suffer. Adding Redis as the notification system eliminates that load.

**Comment by guettli** [comment]
Yes, you are right. Implementing exchangeable backends could be added later. If you don't need it now, don't do it. It could be done later.
